### ISSUE TITLE
please cut a new release on NPM

### ISSUE THREAD

**Issue by gdams** [nodejs/node-meeting-agenda#2]
Looks like the latest release on NPM doesn't support the optional ORG arguement

**Comment by Trott** [comment]
I ran `npm version minor` and then tried to run `npm publish` but I do not have permission. Maybe @rvagg can publish it? (I'm not sure who is in the Node.js org on GitHub, but anyone in that could probably publish it too.)

**Comment by rvagg** [comment]
i don't even have this repo cloned anymore, I imagine @mhdawson uses it and publishes? who can I give additional perms to that's going to make use of it? @Trott? Is this you? https://www.npmjs.com/~trott

**Comment by Trott** [comment]
> i don't even have this repo cloned anymore, I imagine @mhdawson uses it and publishes? who can I give additional perms to that's going to make use of it? @Trott? Is this you? https://www.npmjs.com/~trott

Yes, that's me!

**Comment by rvagg** [comment]
should be added now

**Comment by Trott** [comment]
Published 1.1.0 which supports the optional org argument. Thanks everyone.
